#!/bin/bash
# Documented on:
# https://www1.agenziadoganemonopoli.gov.it/siti_inibiti_tabacchi.htm

source common_adm.sh

URL_adm="https://www.adm.gov.it/portale/siti-inibiti-tabacchi"

download_adm 'tabacchi' $LISTS_DIR/tabacchi.new 

