#!/bin/bash

source config.sh

if [ ! -e "$FILE_agcom" ]; then
  test $LOGGING_ENABLE == true && echo "$(date '+%d/%m/%y %H:%M:%S') - WARNING: $FILE_agcom does not exist!" >> $LOGFILE
  echo "WARNING: $FILE_agcom does not exist!" >&2
  if [ ! -e $LISTS_DIR/agcom-ip.new ]; then
    : > $LISTS_DIR/agcom-ip.new
  fi
  exit 0
fi
test $LOGGING_ENABLE == true && echo "$(date '+%d/%m/%y %H:%M:%S') - AGCOM Parsing Started" >> $LOGFILE
./parse_agcom "$FILE_agcom" $LISTS_DIR/agcom.new $LISTS_DIR/agcom-ip.new
# ./parse_aams "$FILE_agcom" lists/agcom.new
